### ISSUE TITLE
Module input questions

### ISSUE THREAD

**Issue by xiangyundeyun** [Yasoz/ControlTraj#1]
Hello, thank you very much for the open source code, I have a question in the masked road Autoencoder place, is the input of this gps of the road or the gps of the track, if it is the gps of the road, it seems that it is difficult to get the gps of the road because each track is different, please can you provide some help, thank you again for the work of you and your team

**Comment by Yasoz** [comment]
Hello, thank you for your interest in our work. 

For obtaining the road segment GPS that the trajectory passes through, it is actually easy to obtain. First of all, each road segment has a GPS description in the [OSM](https://www.openstreetmap.org/). Then, you can use the Map-matching methods in https://github.com/cyang-kth/fmm to get the corresponding road segment set. The above process allows you to construct trajectory-road data pairs for model training. For testing, you can use some sequence of unseen road segments, or construct a random sequence of consecutive road segments.

**Comment by xiangyundeyun** [comment]
Thank you very much for your guidance, I will try to get the gps of the road section in this way. I'd also like to ask one more question, which is why roads and trajs load the same data when loading the data part of the main.py file

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/13/2024 23:01 |
| To | Yasoz/ControlTraj ***@***.***> |
| Cc | Hou ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Yasoz/ControlTraj] Module input questions (Issue #1) |

Hello, thank you for your interest in our work.

For obtaining the road segment GPS that the trajectory passes through, it is actually easy to obtain. First of all, each road segment has a GPS description in the OSM. Then, you can use the Map-matching methods in https://github.com/cyang-kth/fmm to get the corresponding road segment set. The above process allows you to construct trajectory-road data pairs for model training. For testing, you can use some sequence of unseen road segments, or construct a random sequence of consecutive road segments.

**Comment by Yasoz** [comment]
Sorry for the misunderstanding; it was a typo when I organized the code. I have fixed the error. Thanks for the correction. By the way. The following repository provides a few samples of the trajectory-roads data after map matching, which should be helpful to you. https://github.com/mamazi0131/JGRM

**Comment by xiangyundeyun** [comment]
Thank you very much for your reply again, it was a great help to me.


| |
hhl661010
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/14/2024 11:14 |
| To | ***@***.***> |
| Cc | Hou ***@***.***> ,
***@***.***> |
| Subject | Re: [Yasoz/ControlTraj] Module input questions (Issue #1) |

Sorry for the misunderstanding; it was a typo when I organized the code. I have fixed the error. Thanks for the correction. By the way. The following repository provides a few samples of the trajectory-roads data after map matching, which should be helpful to you. https://github.com/mamazi0131/JGRM
